"use client";

import { Check, FileText, Save, Sparkles, UserCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { VersionType } from "@/lib/enums";
import {
  markLegalReviewCompleteAction,
  saveHumanFinalAction,
} from "@/lib/actions";
import type { RequestView } from "@/lib/viewModels";
import { cn } from "@/lib/utils";

const defaultFinal =
  "Le client doit prendre connaissance de l’ensemble des frais applicables avant de signer la convention.";

export default function HumanReviewEditor({ request }: { request: RequestView }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const aiDraft = request.versions.find(
    (version) => version.type === VersionType.AI_DRAFT
  );
  const humanFinal = request.versions.find(
    (version) => version.type === VersionType.HUMAN_FINAL
  );
  const source = request.versions.find(
    (version) => version.type === VersionType.SOURCE_EXTRACT
  );
  const [content, setContent] = useState(humanFinal?.content ?? defaultFinal);
  const [notes, setNotes] = useState(
    humanFinal?.notes ??
      "Adjusted for formal Quebec French legal phrasing and client-approved disclosure terminology."
  );
  const [message, setMessage] = useState("");

  const save = () => {
    setMessage("");
    startTransition(async () => {
      const result = await saveHumanFinalAction(request.id, content, notes);
      setMessage(result.ok ? "Human final saved." : result.error);
      router.refresh();
    });
  };

  const completeLegal = () => {
    setMessage("");
    startTransition(async () => {
      const result = await markLegalReviewCompleteAction(request.id);
      setMessage(result.ok ? "Legal review marked complete." : result.error);
      router.refresh();
    });
  };

  return (
    <section
      id="review"
      className="overflow-hidden rounded-xl border border-border bg-panel-card shadow-panel"
    >
      <div className="border-b border-border px-5 py-3.5">
        <div className="flex items-center justify-between">
          <div>
            <div className="text-[11px] uppercase tracking-[0.18em] text-ink-muted">
              Human Review
            </div>
            <h2 className="font-serif text-lg text-ink">
              Editable human-verified final
            </h2>
          </div>
          <div className="hidden items-center gap-1.5 rounded-full bg-blue-50 px-2.5 py-1 text-[11px] text-brand-blue ring-1 ring-blue-200 md:inline-flex">
            <UserCheck className="h-3 w-3" />
            Certified review workspace
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-0 border-b border-border md:grid-cols-2">
        <Pane
          title="Source Text"
          icon={<FileText className="h-3.5 w-3.5" />}
          subtitle={request.sourceLanguage}
        >
          <p className="font-serif text-[15px] leading-relaxed text-ink/90">
            {source?.content ?? "No extracted source text. Use the uploaded document metadata."}
          </p>
        </Pane>
        <Pane
          title="AI First Draft"
          icon={<Sparkles className="h-3.5 w-3.5" />}
          subtitle={aiDraft ? `Generated by ${aiDraft.createdBy}` : "Pending"}
        >
          {aiDraft ? <HighlightedAiDraft /> : <p className="text-sm text-ink-muted">Generate an AI draft to begin review.</p>}
        </Pane>
      </div>

      <div className="grid grid-cols-1 gap-0 md:grid-cols-2">
        <Pane
          title="Diff Highlights"
          icon={<UserCheck className="h-3.5 w-3.5" />}
          subtitle="Human legal improvements"
        >
          <HighlightedHumanFinal />
        </Pane>
        <div className="bg-slate-50/60 p-5">
          <label className="block">
            <span className="text-[11px] uppercase tracking-[0.16em] text-ink-muted">
              Human final translation
            </span>
            <textarea
              value={content}
              onChange={(event) => setContent(event.target.value)}
              rows={7}
              className="mt-2 w-full resize-none rounded-lg border border-border bg-white p-3 font-serif text-sm leading-relaxed text-ink focus:border-brand-blue/50 focus:outline-none"
            />
          </label>
          <label className="mt-3 block">
            <span className="text-[11px] uppercase tracking-[0.16em] text-ink-muted">
              Reviewer notes
            </span>
            <textarea
              value={notes}
              onChange={(event) => setNotes(event.target.value)}
              rows={3}
              className="mt-2 w-full resize-none rounded-lg border border-border bg-white p-3 text-sm leading-relaxed text-ink focus:border-brand-blue/50 focus:outline-none"
            />
          </label>
          <div className="mt-4 flex flex-wrap gap-2">
            <button
              type="button"
              onClick={save}
              disabled={pending || !aiDraft}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium",
                aiDraft
                  ? "bg-shell-900 text-white hover:bg-shell-800"
                  : "cursor-not-allowed bg-slate-100 text-slate-400"
              )}
            >
              <Save className="h-3.5 w-3.5" />
              Save Human Final
            </button>
            <button
              type="button"
              onClick={completeLegal}
              disabled={pending || !humanFinal}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium",
                humanFinal
                  ? "bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200 hover:bg-emerald-100"
                  : "cursor-not-allowed bg-slate-100 text-slate-400"
              )}
            >
              <Check className="h-3.5 w-3.5" />
              {request.legalReviewAt ? "Legal Review Complete" : "Mark Legal Review Complete"}
            </button>
          </div>
          {message && (
            <div className="mt-3 rounded-lg border border-border bg-white px-3 py-2 text-xs text-ink-muted">
              {message}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

function HighlightedAiDraft() {
  return (
    <p className="font-serif text-[15px] leading-relaxed text-ink/90">
      Le client doit{" "}
      <span className="rounded bg-red-100/70 px-1 text-red-700 line-through decoration-red-400/70">
        comprendre
      </span>{" "}
      <span className="rounded bg-red-100/70 px-1 text-red-700 line-through decoration-red-400/70">
        tous les frais
      </span>{" "}
      avant de signer{" "}
      <span className="rounded bg-red-100/70 px-1 text-red-700 line-through decoration-red-400/70">
        l&apos;accord
      </span>
      .
    </p>
  );
}

function HighlightedHumanFinal() {
  return (
    <p className="font-serif text-[15px] leading-relaxed text-ink">
      Le client doit{" "}
      <span className="rounded bg-emerald-100/70 px-1 text-emerald-800 underline decoration-emerald-500/60 underline-offset-2">
        prendre connaissance
      </span>{" "}
      de{" "}
      <span className="rounded bg-emerald-100/70 px-1 text-emerald-800 underline decoration-emerald-500/60 underline-offset-2">
        l&apos;ensemble des frais applicables
      </span>{" "}
      avant de signer{" "}
      <span className="rounded bg-emerald-100/70 px-1 text-emerald-800 underline decoration-emerald-500/60 underline-offset-2">
        la convention
      </span>
      .
    </p>
  );
}

function Pane({
  title,
  icon,
  subtitle,
  children,
}: {
  title: string;
  icon: React.ReactNode;
  subtitle: string;
  children: React.ReactNode;
}) {
  return (
    <div className="border-border bg-white p-5 md:border-r">
      <div className="flex items-center gap-2 text-xs">
        <div className="flex h-6 w-6 items-center justify-center rounded-md bg-blue-50 text-brand-blue ring-1 ring-blue-200">
          {icon}
        </div>
        <div>
          <div className="font-medium text-ink">{title}</div>
          <div className="text-[10px] uppercase tracking-[0.14em] text-ink-muted">
            {subtitle}
          </div>
        </div>
      </div>
      <div className="mt-3">{children}</div>
    </div>
  );
}
