import type {
  AuditEvent,
  GlossaryEntry,
  TranslationDocument,
} from "./types";

export const PRIMARY_DOC_ID = "NA-2026-0418";

export const initialDocuments: TranslationDocument[] = [
  {
    id: PRIMARY_DOC_ID,
    title: "Consumer Credit Disclosure – French Canada",
    client: "MapleBank Legal",
    documentType: "Regulated financial disclosure",
    industry: "Banking / Financial Services",
    sourceLanguage: "English",
    targetLanguage: "French Canadian",
    risk: "High",
    riskScore: 87,
    status: "Human legal review",
    deadline: "6h",
    confidence: 91,
    certificateStatus: "Pending",
    certificateId: "NA-CERT-2026-0418",
    reviewStatus: "In Progress",
    approvalStatus: "Not Started",
    complianceStatus: "Not Started",
    terminologyStatus: "In Progress",
    aiDraftSeconds: 138,
    timeSavedPct: 41,
    reasonsFlagged: [
      "Regulated financial disclosure",
      "Quebec French terminology required",
      "Legal wording sensitivity",
      "Client-approved term conflicts detected",
      "Potential reputational risk if wording is inaccurate",
    ],
    assignedTeam: [
      "Certified legal translator",
      "Compliance editor",
      "Final approver",
    ],
    clientVisibleSummary:
      "This request was classified as high risk because it contains regulated financial disclosure language, Quebec French terminology requirements, and legally sensitive wording.",
    pipeline: {
      Submitted: "complete",
      "AI Draft": "complete",
      "Risk Scored": "complete",
      "Human Review": "active",
      "Compliance Check": "pending",
      "Client Approval": "pending",
      "Trust Certificate": "locked",
    },
  },
  {
    id: "NA-2026-0142",
    title: "Terms of Use Update – Quebec",
    client: "SoftLayer Cloud",
    documentType: "Regulated terms of use",
    industry: "Cloud / SaaS",
    sourceLanguage: "English",
    targetLanguage: "French Canadian",
    risk: "High",
    riskScore: 78,
    status: "Awaiting approval",
    deadline: "4h",
    confidence: 92,
    certificateStatus: "Ready",
    certificateId: "NA-CERT-2026-0142",
    reviewStatus: "Complete",
    approvalStatus: "In Progress",
    complianceStatus: "Complete",
    terminologyStatus: "Complete",
    aiDraftSeconds: 121,
    timeSavedPct: 48,
    reasonsFlagged: [
      "Public-facing legal terms",
      "Quebec consumer protection language",
      "Brand reputational sensitivity",
    ],
    assignedTeam: ["Legal translator", "Compliance editor"],
    clientVisibleSummary:
      "Final wording aligned with Quebec consumer protection requirements. Awaiting your final approval before certificate issue.",
    pipeline: {
      Submitted: "complete",
      "AI Draft": "complete",
      "Risk Scored": "complete",
      "Human Review": "complete",
      "Compliance Check": "complete",
      "Client Approval": "active",
      "Trust Certificate": "pending",
    },
  },
  {
    id: "NA-2026-0139",
    title: "Internal HR Memo – Spanish",
    client: "NorthStar Retail",
    documentType: "Internal HR communication",
    industry: "Retail",
    sourceLanguage: "English",
    targetLanguage: "Spanish",
    risk: "Low",
    riskScore: 22,
    status: "Completed",
    deadline: "Complete",
    confidence: 98,
    certificateStatus: "Issued",
    certificateId: "NA-CERT-2026-0139",
    reviewStatus: "Complete",
    approvalStatus: "Complete",
    complianceStatus: "Complete",
    terminologyStatus: "Complete",
    aiDraftSeconds: 64,
    timeSavedPct: 62,
    reasonsFlagged: [
      "Internal-only audience",
      "No regulated content",
      "Standard HR phrasing",
    ],
    assignedTeam: ["AI-assisted reviewer"],
    clientVisibleSummary:
      "Low-risk internal communication. Auto-approved by Nortam Assure with light human spot-check.",
    pipeline: {
      Submitted: "complete",
      "AI Draft": "complete",
      "Risk Scored": "complete",
      "Human Review": "complete",
      "Compliance Check": "complete",
      "Client Approval": "complete",
      "Trust Certificate": "complete",
    },
  },
  {
    id: "NA-2026-0411",
    title: "Medical Device Warning Label – German",
    client: "Veridian Health",
    documentType: "Regulated medical device label",
    industry: "Healthcare / MedTech",
    sourceLanguage: "English",
    targetLanguage: "German",
    risk: "High",
    riskScore: 91,
    status: "Compliance check",
    deadline: "9h",
    confidence: 89,
    certificateStatus: "Pending",
    certificateId: "NA-CERT-2026-0411",
    reviewStatus: "Complete",
    approvalStatus: "Not Started",
    complianceStatus: "In Progress",
    terminologyStatus: "Complete",
    aiDraftSeconds: 154,
    timeSavedPct: 38,
    reasonsFlagged: [
      "Patient safety language",
      "EU MDR regulatory wording",
      "Strict German pharmacovigilance terminology",
    ],
    assignedTeam: ["Healthcare translation specialist", "Compliance editor"],
    clientVisibleSummary:
      "Patient-safety language under final compliance verification before certificate.",
    pipeline: {
      Submitted: "complete",
      "AI Draft": "complete",
      "Risk Scored": "complete",
      "Human Review": "complete",
      "Compliance Check": "active",
      "Client Approval": "pending",
      "Trust Certificate": "locked",
    },
  },
  {
    id: "NA-2026-0406",
    title: "Streaming Trailer Subtitles – Japanese",
    client: "Aurora Studios",
    documentType: "Entertainment / subtitle file",
    industry: "Media & Entertainment",
    sourceLanguage: "English",
    targetLanguage: "Japanese",
    risk: "Medium",
    riskScore: 54,
    status: "Cultural review",
    deadline: "1d",
    confidence: 94,
    certificateStatus: "Pending",
    certificateId: "NA-CERT-2026-0406",
    reviewStatus: "In Progress",
    approvalStatus: "Not Started",
    complianceStatus: "Not Started",
    terminologyStatus: "In Progress",
    aiDraftSeconds: 92,
    timeSavedPct: 55,
    reasonsFlagged: [
      "Cultural nuance",
      "Brand tone for streaming release",
      "Market-specific idiom adaptation",
    ],
    assignedTeam: ["Cultural localization reviewer"],
    clientVisibleSummary:
      "Cultural adaptation in progress. Subtitle timing and idiomatic phrasing reviewed for the JP market.",
    pipeline: {
      Submitted: "complete",
      "AI Draft": "complete",
      "Risk Scored": "complete",
      "Human Review": "active",
      "Compliance Check": "pending",
      "Client Approval": "pending",
      "Trust Certificate": "locked",
    },
  },
  {
    id: "NA-2026-0395",
    title: "Product Fee Notice – French Canada",
    client: "MapleBank Legal",
    documentType: "Customer-facing fee notice",
    industry: "Banking / Financial Services",
    sourceLanguage: "English",
    targetLanguage: "French Canadian",
    risk: "Medium",
    riskScore: 61,
    status: "Compliance check",
    deadline: "1d",
    confidence: 95,
    certificateStatus: "Pending",
    certificateId: "NA-CERT-2026-0395",
    reviewStatus: "Complete",
    approvalStatus: "Not Started",
    complianceStatus: "In Progress",
    terminologyStatus: "Complete",
    aiDraftSeconds: 88,
    timeSavedPct: 47,
    reasonsFlagged: [
      "Customer-facing pricing language",
      "Quebec disclosure formatting",
    ],
    assignedTeam: ["Legal translator", "Compliance editor"],
    clientVisibleSummary:
      "Pricing disclosure under final compliance check before certificate issue.",
    pipeline: {
      Submitted: "complete",
      "AI Draft": "complete",
      "Risk Scored": "complete",
      "Human Review": "complete",
      "Compliance Check": "active",
      "Client Approval": "pending",
      "Trust Certificate": "locked",
    },
  },
];

export const initialAuditTrail: AuditEvent[] = [
  {
    id: "ae-1",
    time: "09:14 AM",
    actor: "Client",
    action: "MapleBank Legal uploaded document",
    status: "complete",
  },
  {
    id: "ae-2",
    time: "09:16 AM",
    actor: "Nortam Assure AI",
    action: "AI first draft generated",
    status: "complete",
  },
  {
    id: "ae-3",
    time: "09:17 AM",
    actor: "Risk Intelligence",
    action: "Risk score assigned: High",
    status: "complete",
  },
  {
    id: "ae-4",
    time: "09:21 AM",
    actor: "Amira Chen, Legal Translator",
    action: "Legal reviewer edited clause 4.2",
    status: "complete",
  },
  {
    id: "ae-5",
    time: "09:28 AM",
    actor: "Terminology Engine",
    action: "Terminology conflict resolved",
    status: "complete",
  },
  {
    id: "ae-6",
    time: "09:35 AM",
    actor: "David Morgan, Compliance Editor",
    action: "Compliance editor approved wording",
    status: "complete",
  },
  {
    id: "ae-7",
    time: "09:41 AM",
    actor: "Priya Shah, Final Approver",
    action: "Final approver ready",
    status: "complete",
  },
  {
    id: "ae-8",
    time: "Pending",
    actor: "Certificate Engine",
    action: "Nortam Trust Certificate",
    status: "pending",
  },
];

export const approvedGlossary: GlossaryEntry[] = [
  { english: "Agreement", approved: "Convention" },
  { english: "Fees", approved: "Frais applicables" },
  { english: "Disclosure", approved: "Document d’information" },
  { english: "Consumer", approved: "Consommateur" },
  { english: "Must", approved: "Doit" },
];

export const reviewerComments = [
  {
    role: "Legal Reviewer",
    name: "Amira Chen",
    note: "Term adjusted to match approved Quebec disclosure language.",
  },
  {
    role: "Compliance Editor",
    name: "David Morgan",
    note: "Confirmed regulated phrase alignment.",
  },
  {
    role: "Final Approver",
    name: "Priya Shah",
    note: "Ready for certificate after terminology check.",
  },
];

export const riskBreakdown = [
  { label: "Legal sensitivity", value: 32, max: 35 },
  { label: "Industry regulation", value: 24, max: 25 },
  { label: "Brand / confidentiality risk", value: 18, max: 20 },
  { label: "Cultural nuance", value: 8, max: 10 },
  { label: "AI confidence gap", value: 5, max: 10 },
];

export const mediaExpansion = [
  "Subtitle review",
  "Dubbing script adaptation",
  "Cultural sensitivity checks",
  "Voice consent tracking",
  "Brand tone verification",
  "Market-specific localization notes",
];
